login:
    path:     /login
    defaults: { _controller: LoginBundle:Default:index }
dashboard:
    path:     /dashboard
    defaults: { _controller: AppBundle:Dashboard:index }

logout:
    path:     /logout
    defaults: { _controller: LoginBundle:Default:logout }

