login:
    path:     /login
    defaults: { _controller: LoginBundle:Default:index }

logout:
    path:     /logout
    defaults: { _controller: LoginBundle:Default:logout }

home:
    path:     /
    defaults: { _controller: LoginBundle:Default:index }
